### ISSUE TITLE
quick thing re pkg.add in readme

### ISSUE THREAD

**Issue by ym-han** [shashi/FileTrees.jl#24]
I'm on Julia 1.5, and it required a url flag for the url in the pkg.add. That is, it required

```
using Pkg
Pkg.add(url = "https://github.com/shashi/FileTrees.jl")
```
and not just

```
using Pkg
Pkg.add("https://github.com/shashi/FileTrees.jl")
```

**Comment by shashi** [comment]
Oh thanks!

I updated the readme to install the latest tagged release.
