### ISSUE TITLE
Fetch value stored at node in Windows 10

### ISSUE THREAD

**Issue by evadknarf** [shashi/FileTrees.jl#31]
I have a dataframe stored at the following file node. but unable to retrieve it. I'm not sure if it is a bug...

And also on windows, absolute file path with two backslashes (\\) were not regconised. I will try to attached a screenshot for this as well.

![image](https://user-images.githubusercontent.com/14981695/92308259-19e61800-efcf-11ea-83b5-5c9ba79c8884.png)

**Comment by shashi** [comment]
You need `values` here to get all the values in a tree.

`get` will only get the value of the node you pass to it, in which case it's the whole tree node which has no value...

**Comment by evadknarf** [comment]
Thanks it works!

I read the documentation, didn't find the `values` function in the API. Is the documentation up to date?
